version: 0.2
env:
  variables:
phases:
  install:
    runtime-versions:
      nodejs:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build 

